#!/usr/bin/env bash
# =============================================================================
# deploy.sh — Deployment script for Enterprise Home SOC Lab
# Author: SOC Lab Project
# Description: Installs Docker (if missing), pulls all images, launches the
#              full stack via docker-compose, waits for health checks, and
#              prints access URLs on success.
# Usage: sudo bash deploy.sh
# =============================================================================

set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }

# ── Environment variables (override via export before running) ────────────────
: "${SOC_DIR:=$(cd "$(dirname "$0")/../.." && pwd)}"
: "${COMPOSE_FILE:=${SOC_DIR}/scripts/setup/docker-compose.yml}"
: "${ENV_FILE:=${SOC_DIR}/scripts/setup/.env}"
: "${WAZUH_MANAGER_PASSWORD:=WazuhAdmin_S3cur3!}"
: "${ELASTIC_PASSWORD:=ElasticAdmin_S3cur3!}"
: "${THEHIVE_SECRET:=TheHiveSecret_S3cur3!}"
: "${SHUFFLE_SECRET:=ShuffleSecret_S3cur3!}"

REQUIRED_RAM_GB=20
REQUIRED_DISK_GB=40

# ── Pre-flight checks ─────────────────────────────────────────────────────────
preflight_checks() {
    info "Running pre-flight checks..."

    # RAM check
    local ram_kb
    ram_kb=$(grep MemTotal /proc/meminfo | awk '{print $2}')
    local ram_gb=$(( ram_kb / 1024 / 1024 ))
    if [[ $ram_gb -lt $REQUIRED_RAM_GB ]]; then
        warn "System has ${ram_gb}GB RAM. Recommended minimum is ${REQUIRED_RAM_GB}GB."
    else
        success "RAM: ${ram_gb}GB available"
    fi

    # Disk check
    local disk_gb
    disk_gb=$(df -BG / | awk 'NR==2 {gsub("G",""); print $4}')
    if [[ $disk_gb -lt $REQUIRED_DISK_GB ]]; then
        warn "Only ${disk_gb}GB free disk space. Recommended: ${REQUIRED_DISK_GB}GB."
    else
        success "Disk: ${disk_gb}GB free"
    fi

    # Root check
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root (sudo)."
    fi
    success "Running as root"
}

# ── Install Docker ────────────────────────────────────────────────────────────
install_docker() {
    if command -v docker &>/dev/null; then
        success "Docker already installed: $(docker --version)"
        return
    fi

    info "Installing Docker..."
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg lsb-release

    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/debian \
$(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
        > /etc/apt/sources.list.d/docker.list

    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
        docker-buildx-plugin docker-compose-plugin

    systemctl enable --now docker
    success "Docker installed: $(docker --version)"
}

# ── Install Docker Compose (standalone) ──────────────────────────────────────
install_docker_compose() {
    if docker compose version &>/dev/null 2>&1; then
        success "Docker Compose plugin available: $(docker compose version)"
        return
    fi
    if command -v docker-compose &>/dev/null; then
        success "docker-compose standalone: $(docker-compose --version)"
        return
    fi

    info "Installing Docker Compose standalone..."
    local version="2.27.0"
    local arch
    arch=$(uname -m | sed 's/x86_64/x86_64/;s/aarch64/aarch64/')
    curl -fsSL \
        "https://github.com/docker/compose/releases/download/v${version}/docker-compose-linux-${arch}" \
        -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    success "docker-compose installed: $(docker-compose --version)"
}

# ── Tune kernel parameters for Elasticsearch ─────────────────────────────────
tune_kernel() {
    info "Tuning kernel parameters for Elasticsearch..."
    sysctl -w vm.max_map_count=262144 > /dev/null
    echo "vm.max_map_count=262144" > /etc/sysctl.d/99-soc-lab.conf
    success "vm.max_map_count set to 262144"
}

# ── Generate .env file ────────────────────────────────────────────────────────
generate_env() {
    info "Generating ${ENV_FILE}..."
    cat > "${ENV_FILE}" <<EOF
# Auto-generated by deploy.sh — $(date)
# Edit secrets before production use!

WAZUH_MANAGER_PASSWORD=${WAZUH_MANAGER_PASSWORD}
ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
THEHIVE_SECRET=${THEHIVE_SECRET}
SHUFFLE_SECRET=${SHUFFLE_SECRET}

# Versions
WAZUH_VERSION=4.7.3
ELASTIC_VERSION=8.13.4

# Network
COMPOSE_PROJECT_NAME=soc-lab
EOF
    success ".env file created at ${ENV_FILE}"
}

# ── Docker Compose up ─────────────────────────────────────────────────────────
start_stack() {
    info "Pulling Docker images (this may take 10-20 minutes)..."
    docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" pull

    info "Starting SOC stack..."
    docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" up -d

    success "All containers started"
}

# ── Health checks ─────────────────────────────────────────────────────────────
wait_for_service() {
    local name="$1"
    local url="$2"
    local max_attempts="${3:-30}"
    local wait_sec="${4:-10}"

    info "Waiting for ${name} to become healthy..."
    local attempt=1
    while [[ $attempt -le $max_attempts ]]; do
        if curl -sk --max-time 5 "${url}" -o /dev/null; then
            success "${name} is up!"
            return 0
        fi
        echo -ne "  Attempt ${attempt}/${max_attempts}...\r"
        sleep "$wait_sec"
        (( attempt++ ))
    done
    warn "${name} did not respond after $((max_attempts * wait_sec))s — check logs with: docker compose logs"
    return 1
}

health_checks() {
    info "Running health checks (allow up to 5 minutes per service)..."
    wait_for_service "Elasticsearch"   "http://localhost:9200"          30 10
    wait_for_service "Kibana"          "http://localhost:5601"          36 10
    wait_for_service "Wazuh Dashboard" "https://localhost:443"          30 10
    wait_for_service "TheHive"         "http://localhost:9000"          30 10
    wait_for_service "Shuffle"         "http://localhost:3001"          20 10
}

# ── Print access info ─────────────────────────────────────────────────────────
print_access_info() {
    local host_ip
    host_ip=$(hostname -I | awk '{print $1}')

    echo ""
    echo -e "${BOLD}${GREEN}════════════════════════════════════════════════════════${RESET}"
    echo -e "${BOLD}${GREEN}  SOC LAB DEPLOYMENT COMPLETE${RESET}"
    echo -e "${BOLD}${GREEN}════════════════════════════════════════════════════════${RESET}"
    echo ""
    echo -e "${BOLD}Service Access URLs:${RESET}"
    echo -e "  🛡  Wazuh Dashboard  : ${CYAN}https://${host_ip}:443${RESET}"
    echo -e "      Username: admin | Password: ${WAZUH_MANAGER_PASSWORD}"
    echo ""
    echo -e "  📊  Kibana           : ${CYAN}http://${host_ip}:5601${RESET}"
    echo -e "      Username: elastic | Password: ${ELASTIC_PASSWORD}"
    echo ""
    echo -e "  🔍  Elasticsearch    : ${CYAN}http://${host_ip}:9200${RESET}"
    echo ""
    echo -e "  🐝  TheHive          : ${CYAN}http://${host_ip}:9000${RESET}"
    echo -e "      Default: admin@thehive.local / secret"
    echo ""
    echo -e "  🔄  Shuffle SOAR     : ${CYAN}http://${host_ip}:3001${RESET}"
    echo ""
    echo -e "${YELLOW}Next steps:${RESET}"
    echo "  1. Run: bash scripts/setup/deploy-linux-agent.sh"
    echo "  2. Import Kibana dashboards: elastic/dashboards/"
    echo "  3. Load Wazuh rules: wazuh/rules/"
    echo "  4. Run health check: python3 scripts/automation/health-check.py"
    echo ""
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
    echo -e "${BOLD}${CYAN}"
    echo "  ███████╗ ██████╗  ██████╗    ██╗      █████╗ ██████╗ "
    echo "  ██╔════╝██╔═══██╗██╔════╝    ██║     ██╔══██╗██╔══██╗"
    echo "  ███████╗██║   ██║██║         ██║     ███████║██████╔╝"
    echo "  ╚════██║██║   ██║██║         ██║     ██╔══██║██╔══██╗"
    echo "  ███████║╚██████╔╝╚██████╗    ███████╗██║  ██║██████╔╝"
    echo "  ╚══════╝ ╚═════╝  ╚═════╝    ╚══════╝╚═╝  ╚═╝╚═════╝ "
    echo -e "${RESET}"
    echo -e "  Enterprise Home SOC Lab — Deployment Script"
    echo ""

    preflight_checks
    install_docker
    install_docker_compose
    tune_kernel
    generate_env
    start_stack
    health_checks
    print_access_info
}

main "$@"
